spring:
  messages:
    basename: locale/messages
    cache-seconds: -1
    encoding: UTF-8
    fallback-to-system-locale: true 
logging:
  level:
    org.springframework.web: error
    pl.misnet.taskmonitor: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"